openapi: "3.0.1"
info:
  title: "Lord.Gym.API"
  version: "1.0"
paths:
  /api/v1/Account/register:
    post:
      tags:
        - "Account"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
          text/json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
          application/*+json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
      responses:
        "200":
          description: "Success"
  /api/v1/Account/login:
    post:
      tags:
        - "Account"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
          text/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
          application/*+json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "200":
          description: "Success"
  /api/v1/Account:
    get:
      tags:
        - "Account"
      responses:
        "200":
          description: "Success"
  /api/v1/Message:
    post:
      tags:
        - "Message"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMessageCommand"
          text/json:
            schema:
              $ref: "#/components/schemas/CreateMessageCommand"
          application/*+json:
            schema:
              $ref: "#/components/schemas/CreateMessageCommand"
      responses:
        "200":
          description: "Success"
components:
  schemas:
    CreateMessageCommand:
      type: "object"
      properties:
        content:
          type: "string"
          nullable: true
        timestamp:
          type: "string"
          format: "date-time"
        from:
          type: "string"
          format: "uuid"
        room:
          type: "string"
          nullable: true
      additionalProperties: false
    LoginDto:
      type: "object"
      properties:
        username:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
      additionalProperties: false
    RegisterDto:
      type: "object"
      properties:
        userName:
          type: "string"
          nullable: true
        email:
          type: "string"
          nullable: true
        firstName:
          type: "string"
          nullable: true
        lastName:
          type: "string"
          nullable: true
        emailConfirmed:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
      additionalProperties: false
